### ISSUE TITLE
some users have no github activity tab

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/WebsiteOne#1632]
No github activity tab, and karma doesn't seem to be increasing.

E.g.,
https://www.agileventures.org/users/matt-lindsey?tab=activity

**Comment by tansaku** [comment]
no activity tab message is appearing

[no activity tab message is appearing](https://www.dropbox.com/s/czbloh5ce47g5lj/Screenshot%202017-04-21%2016.39.05.png?dl=1)

**Comment by mattlindsey** [comment]
Replacing line 21 in projects.rb with following should fix:
  scope :with_github_url, -> { where.not(projects: { github_url: nil  }) }

Just doing some final testing...

**Comment by mattlindsey** [comment]
Test looks good.  Will do a PR.

**Comment by mattlindsey** [comment]
Note that the following should work better (less log messages):
  scope :with_github_url, -> { where.not(github_url: [nil,'']) }

But active record give error on comparison with blank ('').

**Comment by freeranger** [comment]
@mattlindsey @tansaku - this is a related issue: #1630 in that commits are not increasing despite multiple commits.  Perhaps fixing one will fix the other?

**Comment by mattlindsey** [comment]
I get the following error in Octokit stepping through the code.

(byebug) self.contributors('AgileVentures/WebsiteOne')
*** Octokit::TooManyRequests Exception: GET https://api.github.com/repos/AgileVentures/WebsiteOne/contributors: 403 - API rate limit exceeded for 173.48.214.123. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting

@tansaku @mtc2013 @freeranger:  I think using a github api key to make 'authenticated' requests should fix the problem.  Sound right?

**Comment by mattlindsey** [comment]
@tansaku @mtc2013 @freeranger: I think the PR for this issue is all set now since the Activity tab shows up.
Check issue #1630 again, but that one may not be fixed.  There might be more issues, I think.

**Comment by freeranger** [comment]
@mattlindsey still no activity logged for me and Jake, the project leader has no activity at all - he too has commits to this project.  I would suggest for Jake at least, the problem is still as per the title of this issue.  #1630 may well turn out to be something different granted.
